import { Teacher, EducationalQualification } from '../../types';

export const generateSampleTeachers = (
  schoolId: string,
  collegeId: string
): Teacher[] => [
  // -------------------------------------------------------------
  // SCHOOL FACULTY & STAFF
  // -------------------------------------------------------------
  {
    id: 'tch_sch_001',
    instituteId: schoolId,
    teacherId: 'FAC-SCH-1001',
    employeeType: 'teacher',
    indexNumber: '10849201',
    firstName: 'Md. Rafiqul',
    lastName: 'Islam',
    bengaliName: 'মো: রফিকুল ইসলাম',
    fatherName: 'Late Nurul Islam',
    fatherNameBn: 'মরহুম নুরুল ইসলাম',
    motherName: 'Amena Khatun',
    motherNameBn: 'আমেনা খাতুন',
    gender: 'male',
    dateOfBirth: '1975-03-12',
    bloodGroup: 'B+',
    religion: 'Islam',
    maritalStatus: 'married',
    nationalId: '19752691234567890',
    phone: '01711223344',
    email: 'rafiqul.head@school.edu.bd',
    presentAddress: 'House 14, Road 5, Dhanmondi, Dhaka-1205',
    permanentAddress: 'Village: Madhupur, Upazila: Singra, District: Natore',
    designation: 'Headmaster',
    bengaliDesignation: 'প্রধান শিক্ষক',
    departmentName: 'General & Administration',
    employmentNature: 'mpo',
    joiningDate: '2005-01-15',
    experienceYears: 21,
    salaryGrade: 'Grade 7',
    basicSalary: 38000,
    bankAccountNumber: '20501234567890',
    bankName: 'Sonali Bank PLC',
    specialization: 'Institutional Leadership & Mathematics',
    qualifications: [
      {
        id: 'q1',
        degreeTitle: 'M.Sc (Mathematics)',
        majorSubject: 'Applied Mathematics',
        instituteOrUniversity: 'University of Rajshahi',
        passingYear: '1998',
        resultOrGpa: 'First Class',
      },
      {
        id: 'q2',
        degreeTitle: 'B.Ed (Bachelor of Education)',
        majorSubject: 'Pedagogy & Curriculum',
        instituteOrUniversity: 'Govt. Teachers Training College, Dhaka',
        passingYear: '2001',
        resultOrGpa: 'First Class',
      },
    ],
    status: 'active',
    notes: 'National Best Headmaster Award Nominee (2022)',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tch_sch_002',
    instituteId: schoolId,
    teacherId: 'FAC-SCH-1002',
    employeeType: 'teacher',
    indexNumber: '10924810',
    firstName: 'Farhana',
    lastName: 'Yasmin',
    bengaliName: 'ফারহানা ইয়াসমিন',
    fatherName: 'Md. Abdul Jalil',
    fatherNameBn: 'মোঃ আব্দুল জলিল',
    motherName: 'Rokeya Begum',
    motherNameBn: 'রোকেয়া বেগম',
    gender: 'female',
    dateOfBirth: '1982-07-24',
    bloodGroup: 'A+',
    religion: 'Islam',
    maritalStatus: 'married',
    nationalId: '19822695544332211',
    phone: '01819334455',
    email: 'farhana.eng@school.edu.bd',
    presentAddress: 'Apartment 4B, Green Road, Dhaka',
    permanentAddress: 'Sadar, Mymensingh',
    designation: 'Assistant Headmaster',
    bengaliDesignation: 'সহকারী প্রধান শিক্ষক',
    departmentName: 'English',
    employmentNature: 'mpo',
    joiningDate: '2008-04-01',
    experienceYears: 18,
    salaryGrade: 'Grade 8',
    basicSalary: 31000,
    bankAccountNumber: '20509876543210',
    bankName: 'Agrani Bank PLC',
    specialization: 'English Language Teaching (ELT)',
    qualifications: [
      {
        id: 'q3',
        degreeTitle: 'M.A in English',
        majorSubject: 'English Literature & Linguistics',
        instituteOrUniversity: 'University of Dhaka',
        passingYear: '2005',
        resultOrGpa: 'First Class',
      },
      {
        id: 'q4',
        degreeTitle: 'B.Ed',
        majorSubject: 'Secondary Education',
        instituteOrUniversity: 'National University',
        passingYear: '2007',
        resultOrGpa: 'First Class',
      },
    ],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tch_sch_003',
    instituteId: schoolId,
    teacherId: 'FAC-SCH-1003',
    employeeType: 'teacher',
    indexNumber: '11203491',
    firstName: 'Anup Kumar',
    lastName: 'Roy',
    bengaliName: 'অনুপ কুমার রায়',
    fatherName: 'Birendra Nath Roy',
    fatherNameBn: 'বীরেন্দ্রনাথ রায়',
    motherName: 'Shanti Bala Roy',
    motherNameBn: 'শান্তি বালা রায়',
    gender: 'male',
    dateOfBirth: '1986-11-05',
    bloodGroup: 'O+',
    religion: 'Hinduism',
    maritalStatus: 'married',
    nationalId: '19865432109876543',
    phone: '01722334466',
    email: 'anup.math@school.edu.bd',
    presentAddress: '32/B Mirpur-10, Dhaka',
    permanentAddress: 'Dinajpur Sadar, Dinajpur',
    designation: 'Senior Teacher',
    bengaliDesignation: 'সিনিয়র শিক্ষক (গণিত)',
    departmentName: 'Mathematics',
    employmentNature: 'mpo',
    joiningDate: '2012-03-10',
    experienceYears: 14,
    salaryGrade: 'Grade 9',
    basicSalary: 25000,
    specialization: 'Higher Mathematics & Geometry',
    qualifications: [
      {
        id: 'q5',
        degreeTitle: 'B.Sc (Honours) & M.Sc',
        majorSubject: 'Pure Mathematics',
        instituteOrUniversity: 'Jahangirnagar University',
        passingYear: '2010',
        resultOrGpa: 'CGPA 3.65',
      },
    ],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tch_sch_004',
    instituteId: schoolId,
    teacherId: 'FAC-SCH-1004',
    employeeType: 'teacher',
    indexNumber: '11345920',
    firstName: 'Nusrat',
    lastName: 'Jahan',
    bengaliName: 'নুসরাত জাহান',
    fatherName: 'Dr. Kabir Ahmed',
    fatherNameBn: 'ডাঃ কবির আহমেদ',
    motherName: 'Dilruba Parvin',
    motherNameBn: 'দিলরুবা পারভীন',
    gender: 'female',
    dateOfBirth: '1990-09-18',
    bloodGroup: 'AB+',
    religion: 'Islam',
    maritalStatus: 'married',
    nationalId: '19901234567890123',
    phone: '01911998877',
    email: 'nusrat.sci@school.edu.bd',
    presentAddress: 'Sector 4, Uttara, Dhaka',
    permanentAddress: 'Kishoreganj Sadar',
    designation: 'Assistant Teacher',
    bengaliDesignation: 'সহকারী শিক্ষক (বিজ্ঞান)',
    departmentName: 'Science',
    employmentNature: 'permanent',
    joiningDate: '2016-08-01',
    experienceYears: 10,
    salaryGrade: 'Grade 10',
    basicSalary: 21000,
    specialization: 'General Science & Biology',
    qualifications: [
      {
        id: 'q6',
        degreeTitle: 'M.Sc in Botany',
        majorSubject: 'Plant Physiology',
        instituteOrUniversity: 'University of Dhaka',
        passingYear: '2014',
        resultOrGpa: 'CGPA 3.72',
      },
    ],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tch_sch_005',
    instituteId: schoolId,
    teacherId: 'FAC-SCH-1005',
    employeeType: 'teacher',
    indexNumber: '11459203',
    firstName: 'Kazi Mahbubur',
    lastName: 'Rahman',
    bengaliName: 'কাজী মাহবুবুর রহমান',
    fatherName: 'Kazi Aminur Rahman',
    fatherNameBn: 'কাজী আমিনুর রহমান',
    motherName: 'Fatema Begum',
    motherNameBn: 'ফাতেমা বেগম',
    gender: 'male',
    dateOfBirth: '1988-02-14',
    bloodGroup: 'O+',
    religion: 'Islam',
    maritalStatus: 'married',
    nationalId: '19881234567890123',
    phone: '01677889900',
    email: 'mahbub.ict@school.edu.bd',
    presentAddress: 'Farmgate, Tejgaon, Dhaka',
    permanentAddress: 'Brahmanbaria Sadar',
    designation: 'Assistant Teacher',
    bengaliDesignation: 'সহকারী শিক্ষক (আইসিটি)',
    departmentName: 'ICT',
    employmentNature: 'mpo',
    joiningDate: '2015-02-10',
    experienceYears: 11,
    salaryGrade: 'Grade 10',
    basicSalary: 21000,
    specialization: 'Computer Science & ICT Literacy',
    qualifications: [
      {
        id: 'q7',
        degreeTitle: 'B.Sc in CSE',
        majorSubject: 'Computer Science & Engineering',
        instituteOrUniversity: 'Daffodil International University',
        passingYear: '2012',
        resultOrGpa: 'CGPA 3.80',
      },
    ],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'stf_sch_006',
    instituteId: schoolId,
    teacherId: 'STF-SCH-2001',
    employeeType: 'staff',
    indexNumber: '20194820',
    firstName: 'Kamal Hossain',
    lastName: 'Akand',
    bengaliName: 'কামাল হোসেন আকন্দ',
    gender: 'male',
    dateOfBirth: '1984-06-20',
    bloodGroup: 'B+',
    religion: 'Islam',
    maritalStatus: 'married',
    nationalId: '19841234567890123',
    phone: '01733445566',
    email: 'accounts.school@erp.local',
    presentAddress: 'Lalbagh, Dhaka',
    permanentAddress: 'Munshiganj Sadar',
    designation: 'Accountant & Cashier',
    bengaliDesignation: 'প্রধান হিসাবরক্ষক',
    departmentName: 'Finance & Accounts',
    employmentNature: 'permanent',
    joiningDate: '2010-05-15',
    experienceYears: 16,
    salaryGrade: 'Grade 11',
    basicSalary: 18500,
    specialization: 'School Billing, Cashiering & Banking',
    qualifications: [
      {
        id: 'q8',
        degreeTitle: 'M.Com in Accounting',
        majorSubject: 'Advanced Financial Accounting',
        instituteOrUniversity: 'National University',
        passingYear: '2008',
        resultOrGpa: 'Second Class',
      },
    ],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // -------------------------------------------------------------
  // COLLEGE FACULTY & STAFF
  // -------------------------------------------------------------
  {
    id: 'tch_col_101',
    instituteId: collegeId,
    teacherId: 'FAC-COL-1001',
    employeeType: 'teacher',
    indexNumber: '30194821',
    firstName: 'Dr. Mohammad Nazmul',
    lastName: 'Haque',
    bengaliName: 'ড. মোহাম্মদ নাজমুল হক',
    gender: 'male',
    dateOfBirth: '1970-08-15',
    bloodGroup: 'O+',
    religion: 'Islam',
    maritalStatus: 'married',
    nationalId: '19701234567890123',
    phone: '01712345678',
    email: 'principal.college@erp.local',
    presentAddress: 'Banani DOHS, Dhaka',
    permanentAddress: 'Kotwali, Cumilla',
    designation: 'Principal',
    bengaliDesignation: 'অধ্যক্ষ',
    departmentName: 'Administration & Physics',
    employmentNature: 'mpo',
    joiningDate: '2000-09-01',
    experienceYears: 26,
    salaryGrade: 'Grade 5',
    basicSalary: 48000,
    specialization: 'Quantum Mechanics & Educational Administration',
    qualifications: [
      {
        id: 'q10',
        degreeTitle: 'Ph.D in Physics',
        majorSubject: 'Nuclear Physics',
        instituteOrUniversity: 'University of Dhaka',
        passingYear: '2008',
        resultOrGpa: 'Awarded',
      },
      {
        id: 'q11',
        degreeTitle: 'M.Sc in Physics',
        majorSubject: 'Physics',
        instituteOrUniversity: 'University of Dhaka',
        passingYear: '1995',
        resultOrGpa: 'First Class',
      },
    ],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tch_col_102',
    instituteId: collegeId,
    teacherId: 'FAC-COL-1002',
    employeeType: 'teacher',
    indexNumber: '30284719',
    firstName: 'Begum Rehana',
    lastName: 'Parvin',
    bengaliName: 'বেগম রেহানা পারভীন',
    gender: 'female',
    dateOfBirth: '1976-12-01',
    bloodGroup: 'AB+',
    religion: 'Islam',
    maritalStatus: 'married',
    nationalId: '19761234567890123',
    phone: '01817112233',
    email: 'rehana.chem@college.edu.bd',
    presentAddress: 'Dhanmondi 27, Dhaka',
    permanentAddress: 'Barisal Sadar, Barisal',
    designation: 'Assistant Professor',
    bengaliDesignation: 'সহকারী অধ্যাপক (রসায়ন)',
    departmentName: 'Chemistry',
    employmentNature: 'mpo',
    joiningDate: '2006-11-15',
    experienceYears: 20,
    salaryGrade: 'Grade 6',
    basicSalary: 42000,
    specialization: 'Organic Chemistry & Biochemistry',
    qualifications: [
      {
        id: 'q12',
        degreeTitle: 'M.Sc in Chemistry',
        majorSubject: 'Organic Chemistry',
        instituteOrUniversity: 'University of Rajshahi',
        passingYear: '2001',
        resultOrGpa: 'First Class',
      },
    ],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tch_col_103',
    instituteId: collegeId,
    teacherId: 'FAC-COL-1003',
    employeeType: 'teacher',
    indexNumber: '30491823',
    firstName: 'Syed Tanvir',
    lastName: 'Ahmed',
    bengaliName: 'সৈয়দ তানভীর আহমেদ',
    gender: 'male',
    dateOfBirth: '1989-04-10',
    bloodGroup: 'B+',
    religion: 'Islam',
    maritalStatus: 'single',
    nationalId: '19891234567890123',
    phone: '01912889911',
    email: 'tanvir.acc@college.edu.bd',
    presentAddress: 'Gulshan 1, Dhaka',
    permanentAddress: 'Sylhet Sadar, Sylhet',
    designation: 'Lecturer',
    bengaliDesignation: 'প্রভাষক (হিসাববিজ্ঞান)',
    departmentName: 'Business Studies',
    employmentNature: 'permanent',
    joiningDate: '2018-01-10',
    experienceYears: 8,
    salaryGrade: 'Grade 9',
    basicSalary: 23500,
    specialization: 'Financial Accounting & Taxation',
    qualifications: [
      {
        id: 'q13',
        degreeTitle: 'BBA & MBA (Accounting)',
        majorSubject: 'Accounting & Information Systems',
        instituteOrUniversity: 'University of Dhaka',
        passingYear: '2015',
        resultOrGpa: 'CGPA 3.82',
      },
    ],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'stf_col_104',
    instituteId: collegeId,
    teacherId: 'STF-COL-2001',
    employeeType: 'staff',
    indexNumber: '40192834',
    firstName: 'Md. Shahidul',
    lastName: 'Alam',
    bengaliName: 'মো: শহিদুল আলম',
    gender: 'male',
    dateOfBirth: '1983-05-18',
    bloodGroup: 'A+',
    religion: 'Islam',
    maritalStatus: 'married',
    nationalId: '19831234567890123',
    phone: '01718990011',
    email: 'headclerk.college@erp.local',
    presentAddress: 'Mohammadpur, Dhaka',
    permanentAddress: 'Gazipur Sadar',
    designation: 'Head Clerk & Administrative Officer',
    bengaliDesignation: 'প্রধান সহকারী / হেড ক্লার্ক',
    departmentName: 'College Administration',
    employmentNature: 'mpo',
    joiningDate: '2009-07-01',
    experienceYears: 17,
    salaryGrade: 'Grade 10',
    basicSalary: 21500,
    specialization: 'Board Registration, Form Fillup & Administration',
    qualifications: [
      {
        id: 'q14',
        degreeTitle: 'B.A (Pass)',
        majorSubject: 'Humanities',
        instituteOrUniversity: 'National University',
        passingYear: '2005',
        resultOrGpa: 'Second Division',
      },
    ],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
