import { CertificateRecord, IdCardTemplateConfig, IssuedIdCardRecord } from '../../types';

export const SAMPLE_CERTIFICATES: CertificateRecord[] = [
  // =========================================================
  // CATEGORY A: OFFICIAL / ACADEMIC (English Format)
  // =========================================================
  {
    id: 'cert-tc-01',
    certificateNumber: 'TC-2026-0042',
    certificateType: 'transfer_certificate',
    category: 'official_academic',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-01',
    studentName: 'TANVIR AHMED',
    fatherName: 'MD. RAFIQUL ISLAM',
    motherName: 'SHAHANARA BEGUM',
    rollNumber: 3,
    className: 'Class 10',
    sectionName: 'Section A (Padma)',
    groupName: 'Science',
    session: '2025-2026',
    dateOfBirth: '2009-04-12',
    issueDate: '2026-09-10',
    status: 'issued',
    reasonForLeaving: 'Transfer of father / guardian to Chattogram division',
    conductAndCharacter: 'Exemplary and Disciplined',
    duesClearedUntil: 'September 2026',
    highestClassPassed: 'Class 9 Annual Examination (GPA 4.88)',
    examResultOrGpa: 'GPA 4.88',
    customRemarks: 'He took an active part in inter-school athletics and the annual science exhibition.',
    issuedBy: 'Principal / Headmaster',
    verificationCode: 'VER-TC-892471',
    createdAt: '2026-09-10T10:30:00Z',
    updatedAt: '2026-09-10T10:30:00Z',
  },
  {
    id: 'cert-bnf-02',
    certificateNumber: 'BNF-2026-0089',
    certificateType: 'bonafide_certificate',
    category: 'official_academic',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-03',
    studentName: 'FARHAN CHOWDHURY',
    fatherName: 'KABIR CHOWDHURY',
    motherName: 'FATEMA CHOWDHURY',
    rollNumber: 7,
    className: 'Class 8',
    sectionName: 'Section B (Meghna)',
    groupName: 'General',
    session: '2026',
    dateOfBirth: '2011-06-22',
    issueDate: '2026-09-05',
    status: 'issued',
    conductAndCharacter: 'Very Good and Well-Mannered',
    customRemarks: 'This certificate is issued upon request for official passport renewal and stipend verification purposes.',
    issuedBy: 'Headmaster',
    verificationCode: 'VER-BNF-491024',
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-05T09:00:00Z',
  },
  {
    id: 'cert-tst-03',
    certificateNumber: 'TST-2026-0105',
    certificateType: 'testimonial',
    category: 'official_academic',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-02',
    studentName: 'NUSRAT JAHAN',
    fatherName: 'MD. ABDUL KARIM',
    motherName: 'NASREEN AKHTAR',
    rollNumber: 1,
    className: 'Class 10',
    sectionName: 'Section A (Padma)',
    groupName: 'Science',
    session: '2024-2025',
    dateOfBirth: '2009-02-18',
    issueDate: '2026-08-25',
    status: 'issued',
    boardRoll: '142981',
    boardReg: '1912849201',
    boardName: 'Dhaka',
    examResultOrGpa: 'GPA 5.00 (Golden A+)',
    conductAndCharacter: 'Exemplary and Trustworthy',
    customRemarks: 'She was a dedicated school prefect and debate champion. We wish her every success in her future academic pursuits.',
    issuedBy: 'Principal / Headmaster',
    verificationCode: 'VER-TST-381920',
    createdAt: '2026-08-25T11:15:00Z',
    updatedAt: '2026-08-25T11:15:00Z',
  },
  {
    id: 'cert-adm-04',
    certificateNumber: 'ADM-2026-0034',
    certificateType: 'admission_certificate',
    category: 'official_academic',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-05',
    studentName: 'ABRAR SHAHRIAR',
    fatherName: 'SHAHRIAR HOSSAIN',
    motherName: 'MEHERUN NESA',
    rollNumber: 5,
    className: 'Class 6',
    sectionName: 'Section A',
    groupName: 'General',
    session: '2026',
    dateOfBirth: '2013-08-14',
    issueDate: '2026-01-10',
    status: 'issued',
    admissionDate: '2026-01-05',
    admissionNumber: 'ADM-2026-019',
    conductAndCharacter: 'Disciplined and Obedient',
    customRemarks: 'Officially admitted through competitive merit admission evaluation test.',
    issuedBy: 'Headmaster',
    verificationCode: 'VER-ADM-729104',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },

  // =========================================================
  // CATEGORY B: ACHIEVEMENT (English Format)
  // =========================================================
  {
    id: 'cert-cae-05',
    certificateNumber: 'CAE-2026-0012',
    certificateType: 'academic_excellence',
    category: 'achievement',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-04',
    studentName: 'SADIA AFRIN',
    fatherName: 'DR. MAHFUZUR RAHMAN',
    motherName: 'TAHMINA PARVEEN',
    rollNumber: 1,
    className: 'Class 9',
    sectionName: 'Section A',
    groupName: 'Science',
    session: '2026',
    dateOfBirth: '2010-11-05',
    issueDate: '2026-09-01',
    status: 'issued',
    positionOrRank: '1st Rank (Highest Aggregate Score)',
    examResultOrGpa: 'GPA 5.00 (Total Marks: 948/1000)',
    achievementDetails: 'Awarded for securing the 1st position across all sections in the Half-Yearly Academic Evaluation.',
    customRemarks: 'Maintains supreme consistency in Higher Mathematics, Physics, and English Language.',
    issuedBy: 'Academic Council / Principal',
    verificationCode: 'VER-CAE-819203',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'cert-bst-06',
    certificateNumber: 'BST-2026-0001',
    certificateType: 'best_student',
    category: 'achievement',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-02',
    studentName: 'NUSRAT JAHAN',
    fatherName: 'MD. ABDUL KARIM',
    motherName: 'NASREEN AKHTAR',
    rollNumber: 1,
    className: 'Class 10',
    sectionName: 'Section A',
    groupName: 'Science',
    session: '2025-2026',
    dateOfBirth: '2009-02-18',
    issueDate: '2026-08-30',
    status: 'issued',
    positionOrRank: 'Best Student of the Year',
    achievementDetails: 'Conferred for all-round distinction across academic brilliance, team leadership, ethics, and debating honors.',
    customRemarks: 'An inspiring role model for the entire student body.',
    issuedBy: 'Governing Body & Principal',
    verificationCode: 'VER-BST-990124',
    createdAt: '2026-08-30T11:00:00Z',
    updatedAt: '2026-08-30T11:00:00Z',
  },
  {
    id: 'cert-bat-07',
    certificateNumber: 'BAT-2026-0027',
    certificateType: 'best_attendance',
    category: 'achievement',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-06',
    studentName: 'RAIHAN MAHMUD',
    fatherName: 'MAHMUDUL HASAN',
    motherName: 'FARIDA YASMIN',
    rollNumber: 4,
    className: 'Class 7',
    sectionName: 'Section B',
    groupName: 'General',
    session: '2026',
    dateOfBirth: '2012-05-19',
    issueDate: '2026-09-02',
    status: 'issued',
    positionOrRank: '100% Attendance Record',
    achievementDetails: 'Completed 180 consecutive school instructional days without a single absence or tardiness.',
    customRemarks: 'Commended for exemplary punctuality, discipline, and commitment to learning.',
    issuedBy: 'Headmaster',
    verificationCode: 'VER-BAT-551092',
    createdAt: '2026-09-02T09:30:00Z',
    updatedAt: '2026-09-02T09:30:00Z',
  },

  // =========================================================
  // CATEGORY C: ACTIVITIES (English Format)
  // =========================================================
  {
    id: 'cert-spt-08',
    certificateNumber: 'SPT-2026-0056',
    certificateType: 'sports',
    category: 'activities',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-01',
    studentName: 'TANVIR AHMED',
    fatherName: 'MD. RAFIQUL ISLAM',
    motherName: 'SHAHANARA BEGUM',
    rollNumber: 3,
    className: 'Class 10',
    sectionName: 'Section A',
    groupName: 'Science',
    session: '2026',
    dateOfBirth: '2009-04-12',
    issueDate: '2026-02-28',
    status: 'issued',
    eventOrCompetitionName: 'Inter-School 400m Sprint & Long Jump Championship',
    positionOrRank: 'Champion (Gold Medalist)',
    achievementDetails: 'Secured First Place in the 400-meter sprint and established a new institutional record.',
    customRemarks: 'Demonstrated outstanding athletic endurance and admirable sportsmanship.',
    issuedBy: 'Physical Education Director & Principal',
    verificationCode: 'VER-SPT-330194',
    createdAt: '2026-02-28T14:00:00Z',
    updatedAt: '2026-02-28T14:00:00Z',
  },
  {
    id: 'cert-dbt-09',
    certificateNumber: 'DBT-2026-0019',
    certificateType: 'debate',
    category: 'activities',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-02',
    studentName: 'NUSRAT JAHAN',
    fatherName: 'MD. ABDUL KARIM',
    motherName: 'NASREEN AKHTAR',
    rollNumber: 1,
    className: 'Class 10',
    sectionName: 'Section A',
    groupName: 'Science',
    session: '2026',
    dateOfBirth: '2009-02-18',
    issueDate: '2026-05-15',
    status: 'issued',
    eventOrCompetitionName: 'National Inter-School Parliamentary Debate Festival',
    positionOrRank: 'Best Debater of the Tournament & Champion Team Leader',
    achievementDetails: 'Led the institutional debate delegation to victory through 5 consecutive knockout rounds.',
    customRemarks: 'Praised by national adjudicators for sharp analytical logic and articulate presentation.',
    issuedBy: 'Debating Society Moderator & Principal',
    verificationCode: 'VER-DBT-440182',
    createdAt: '2026-05-15T15:30:00Z',
    updatedAt: '2026-05-15T15:30:00Z',
  },
  {
    id: 'cert-scf-10',
    certificateNumber: 'SCF-2026-0033',
    certificateType: 'science_fair',
    category: 'activities',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-04',
    studentName: 'SADIA AFRIN',
    fatherName: 'DR. MAHFUZUR RAHMAN',
    motherName: 'TAHMINA PARVEEN',
    rollNumber: 1,
    className: 'Class 9',
    sectionName: 'Section A',
    groupName: 'Science',
    session: '2026',
    dateOfBirth: '2010-11-05',
    issueDate: '2026-03-20',
    status: 'issued',
    eventOrCompetitionName: 'Annual Science & Tech Innovation Fair (AI & Eco-Sensors)',
    positionOrRank: '1st Prize - Senior Innovation Division',
    achievementDetails: 'Created an autonomous river-water purity monitoring prototype utilizing solar sensors.',
    customRemarks: 'Project recommended for national science congress representation.',
    issuedBy: 'Science Club Convener & Headmaster',
    verificationCode: 'VER-SCF-661029',
    createdAt: '2026-03-20T12:00:00Z',
    updatedAt: '2026-03-20T12:00:00Z',
  },
];

export const SAMPLE_ID_CARD_TEMPLATES: IdCardTemplateConfig[] = [
  {
    id: 'tmpl-student-portrait',
    name: 'School Student ID (Portrait)',
    type: 'student',
    orientation: 'portrait',
    theme: 'classic_blue',
    showBloodGroup: true,
    showEmergencyPhone: true,
    showAddress: true,
    showQrCode: true,
    showBarcode: true,
    showValidUntil: true,
    validUntilDate: '2026-12-31',
    backSideNoticeBn: 'এই পরিচয়পত্রটি সংশ্লিষ্ট বিদ্যালয়ের সম্পত্তি। পাওয়া গেলে অনুগ্রহপূর্বক নিকটস্থ বিদ্যালয় অফিসে ফেরত দিন।',
    backSideNoticeEn: 'This card is the property of the school. If found, please return to the school administration office.',
  },
  {
    id: 'tmpl-teacher-portrait',
    name: 'Teacher & Staff ID (Portrait)',
    type: 'teacher',
    orientation: 'portrait',
    theme: 'royal_maroon',
    showBloodGroup: true,
    showEmergencyPhone: true,
    showAddress: true,
    showQrCode: true,
    showBarcode: true,
    showValidUntil: true,
    validUntilDate: '2027-12-31',
    backSideNoticeBn: 'অত্র প্রতিষ্ঠানের অনুমোদিত শিক্ষক/কর্মকর্তার পরিচয়পত্র। যেকোনো জরুরি প্রয়োজনে যোগাযোগ করুন।',
    backSideNoticeEn: 'Authorized Faculty / Staff Member of the Institution. Kindly contact for any emergency assistance.',
  },
  {
    id: 'tmpl-student-landscape',
    name: 'College Student ID (Landscape)',
    type: 'student',
    orientation: 'landscape',
    theme: 'emerald_green',
    showBloodGroup: true,
    showEmergencyPhone: true,
    showAddress: false,
    showQrCode: true,
    showBarcode: true,
    showValidUntil: true,
    validUntilDate: '2026-12-31',
    backSideNoticeBn: 'অধ্যক্ষ মহোদয়ের অনুমতি ব্যতীত এই পরিচয়পত্র হস্তান্তর বা নকল করা আইনত দণ্ডনীয়।',
    backSideNoticeEn: 'Strictly non-transferable. Display of ID card is mandatory inside campus premises.',
  },
];

export const DEFAULT_ID_TEMPLATES = SAMPLE_ID_CARD_TEMPLATES;

export const SAMPLE_ISSUED_ID_CARDS: IssuedIdCardRecord[] = [
  {
    id: 'card-stu-01',
    cardType: 'student',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    personId: 'stu-01',
    idNumber: 'STU-2026-0001',
    fullName: 'Tanvir Ahmed',
    bengaliName: 'তানভীর আহমেদ',
    roleOrClass: 'Class 10 (Science)',
    rollOrIndex: 'Roll: 03',
    bloodGroup: 'B+',
    emergencyPhone: '01712-345678',
    issueDate: '2026-01-15',
    validUntil: '2026-12-31',
    status: 'active',
    qrCodeData: 'STU:2026-0001|Tanvir Ahmed|Class 10|Roll:03|Blood:B+|EIIN:134215',
    barcodeData: '20260001',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'card-stu-02',
    cardType: 'student',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    personId: 'stu-02',
    idNumber: 'STU-2026-0002',
    fullName: 'Nusrat Jahan',
    bengaliName: 'নুসরাত জাহান',
    roleOrClass: 'Class 10 (Science)',
    rollOrIndex: 'Roll: 01',
    bloodGroup: 'O+',
    emergencyPhone: '01819-223344',
    issueDate: '2026-01-15',
    validUntil: '2026-12-31',
    status: 'active',
    qrCodeData: 'STU:2026-0002|Nusrat Jahan|Class 10|Roll:01|Blood:O+|EIIN:134215',
    barcodeData: '20260002',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'card-tch-01',
    cardType: 'teacher',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    personId: 'tch-01',
    idNumber: 'FAC-2026-001',
    fullName: 'Mohammad Abdul Hadi',
    bengaliName: 'মোহাম্মদ আব্দুল হাদী',
    roleOrClass: 'Assistant Headmaster',
    rollOrIndex: 'Index: 1048291',
    bloodGroup: 'A+',
    emergencyPhone: '01911-889900',
    issueDate: '2026-01-10',
    validUntil: '2027-12-31',
    status: 'active',
    qrCodeData: 'FAC:2026-001|Mohammad Abdul Hadi|Asst Headmaster|Index:1048291|EIIN:134215',
    barcodeData: 'FAC1048291',
    createdAt: '2026-01-10T08:30:00Z',
  },
];
