import {
  BookItem,
  BookIssueRecord,
  InventoryItem,
  InventoryTransaction,
  VehicleItem,
  TransportRoute,
  TransportAssignment,
  SchoolNotice,
  CalendarEventItem,
} from '../../types';

// ==========================================
// 1. SAMPLE BOOKS (LIBRARY)
// ==========================================
export const SAMPLE_BOOKS: BookItem[] = [
  {
    id: 'book-01',
    instituteId: 'inst-01',
    accessionNumber: 'ACC-2026-001',
    isbn: '978-984-05-1234-5',
    title: 'Anandamath & Selected Works',
    bengaliTitle: 'আনন্দমঠ ও নির্বাচিত উপন্যাস',
    author: 'Bankim Chandra Chattopadhyay',
    publisher: 'Bangla Academy',
    edition: '4th Edition (2022)',
    category: 'literature',
    shelfLocation: 'Shelf L-01, Rack 1',
    totalCopies: 8,
    availableCopies: 6,
    price: 350,
    language: 'bn',
    status: 'available',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'book-02',
    instituteId: 'inst-01',
    accessionNumber: 'ACC-2026-002',
    isbn: '978-984-05-4321-0',
    title: 'Sanchita (Selected Poems)',
    bengaliTitle: 'সঞ্চিতা (কাব্যসংগ্রহ)',
    author: 'Kazi Nazrul Islam',
    publisher: 'Nazrul Institute',
    edition: 'Centenary Edition',
    category: 'literature',
    shelfLocation: 'Shelf L-01, Rack 2',
    totalCopies: 10,
    availableCopies: 7,
    price: 420,
    language: 'bn',
    status: 'available',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'book-03',
    instituteId: 'inst-01',
    accessionNumber: 'ACC-2026-003',
    isbn: '978-984-70-0012-3',
    title: 'The Unfinished Memoirs',
    bengaliTitle: 'অসমাপ্ত আত্মজীবনী',
    author: 'Sheikh Mujibur Rahman',
    publisher: 'The University Press Limited (UPL)',
    edition: 'Revised Edition',
    category: 'history_social',
    shelfLocation: 'Shelf H-02, Rack 1',
    totalCopies: 12,
    availableCopies: 9,
    price: 550,
    language: 'bn',
    status: 'available',
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'book-04',
    instituteId: 'inst-01',
    accessionNumber: 'ACC-2026-004',
    isbn: '978-019-914-567-8',
    title: 'Higher Secondary Physics - Mechanics & Waves',
    bengaliTitle: 'উচ্চ মাধ্যমিক পদার্থবিজ্ঞান (১ম পত্র)',
    author: 'Dr. Shahjahan Tapan & Mohammad Aziz Hasan',
    publisher: 'Hasan Book House',
    edition: '2025 Edition',
    category: 'science',
    shelfLocation: 'Shelf S-03, Rack 1',
    totalCopies: 15,
    availableCopies: 11,
    price: 480,
    language: 'bn',
    status: 'available',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'book-05',
    instituteId: 'inst-01',
    accessionNumber: 'ACC-2026-005',
    isbn: '978-019-914-568-9',
    title: 'Higher Mathematics for Class 9-10 (NCTB)',
    bengaliTitle: 'মাধ্যমিক উচ্চতর গণিত (৯ম-১০ম শ্রেণি)',
    author: 'National Curriculum and Textbook Board (NCTB)',
    publisher: 'Government of Bangladesh',
    edition: '2026 Curriculum',
    category: 'textbook',
    shelfLocation: 'Shelf T-01, Rack 3',
    totalCopies: 25,
    availableCopies: 18,
    price: 180,
    language: 'bn',
    status: 'available',
    createdAt: '2026-01-05T10:00:00Z',
    updatedAt: '2026-01-05T10:00:00Z',
  },
  {
    id: 'book-06',
    instituteId: 'inst-01',
    accessionNumber: 'ACC-2026-006',
    isbn: '978-019-432-843-2',
    title: 'Oxford Advanced Learner’s Dictionary',
    bengaliTitle: 'অক্সফোর্ড অ্যাডভান্সড লার্নার্স ডিকশনারি',
    author: 'A S Hornby',
    publisher: 'Oxford University Press',
    edition: '10th International Edition',
    category: 'reference',
    shelfLocation: 'Shelf R-01, Rack 1',
    totalCopies: 5,
    availableCopies: 3,
    price: 1250,
    language: 'en',
    status: 'available',
    createdAt: '2026-01-18T10:00:00Z',
    updatedAt: '2026-01-18T10:00:00Z',
  },
  {
    id: 'book-07',
    instituteId: 'inst-01',
    accessionNumber: 'ACC-2026-007',
    isbn: '978-984-21-0987-1',
    title: 'A Brief History of Time',
    bengaliTitle: 'কালের সংক্ষিপ্ত ইতিহাস',
    author: 'Stephen Hawking (Trans: Akhtaruzzaman)',
    publisher: 'Sandhani Prakashani',
    edition: '3rd Edition',
    category: 'science',
    shelfLocation: 'Shelf S-03, Rack 2',
    totalCopies: 6,
    availableCopies: 4,
    price: 320,
    language: 'bn',
    status: 'available',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'book-08',
    instituteId: 'inst-01',
    accessionNumber: 'ACC-2026-008',
    isbn: '978-984-50-2345-6',
    title: 'General Chemistry & Laboratory Guide',
    bengaliTitle: 'রসায়ন ও ল্যাবরেটরি নির্দেশিকা',
    author: 'Dr. Soroj Kanti Singha Hazari',
    publisher: 'Hasan Book House',
    edition: '2025 Edition',
    category: 'science',
    shelfLocation: 'Shelf S-03, Rack 3',
    totalCopies: 14,
    availableCopies: 10,
    price: 520,
    language: 'bn',
    status: 'available',
    createdAt: '2026-01-22T10:00:00Z',
    updatedAt: '2026-01-22T10:00:00Z',
  },
];

// ==========================================
// 2. SAMPLE BOOK ISSUES & RETURNS
// ==========================================
export const SAMPLE_BOOK_ISSUES: BookIssueRecord[] = [
  {
    id: 'issue-01',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    bookId: 'book-01',
    bookTitle: 'Anandamath & Selected Works',
    accessionNumber: 'ACC-2026-001',
    borrowerType: 'student',
    borrowerId: 'stu-01',
    borrowerName: 'Tanvir Ahmed',
    borrowerRollOrDesignation: 'Roll: 01',
    borrowerClass: 'Class 10',
    issueDate: '2026-08-20',
    dueDate: '2026-09-03',
    status: 'overdue',
    finePerDay: 2,
    overdueDays: 9,
    fineAmount: 18,
    finePaid: false,
    notes: 'Reminder SMS sent to student',
    issuedBy: 'Md. Shafiqur Rahman (Librarian)',
    createdAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'issue-02',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    bookId: 'book-04',
    bookTitle: 'Higher Secondary Physics - Mechanics & Waves',
    accessionNumber: 'ACC-2026-004',
    borrowerType: 'student',
    borrowerId: 'stu-02',
    borrowerName: 'Nusrat Jahan',
    borrowerRollOrDesignation: 'Roll: 02',
    borrowerClass: 'Class 10',
    issueDate: '2026-09-05',
    dueDate: '2026-09-19',
    status: 'issued',
    finePerDay: 2,
    overdueDays: 0,
    fineAmount: 0,
    finePaid: false,
    issuedBy: 'Md. Shafiqur Rahman (Librarian)',
    createdAt: '2026-09-05T09:30:00Z',
  },
  {
    id: 'issue-03',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    bookId: 'book-06',
    bookTitle: 'Oxford Advanced Learner’s Dictionary',
    accessionNumber: 'ACC-2026-006',
    borrowerType: 'teacher',
    borrowerId: 'tc-01',
    borrowerName: 'Mohammad Faruk Hossain',
    borrowerRollOrDesignation: 'Senior Teacher (English)',
    issueDate: '2026-08-25',
    dueDate: '2026-09-15',
    status: 'issued',
    finePerDay: 0,
    issuedBy: 'Md. Shafiqur Rahman (Librarian)',
    createdAt: '2026-08-25T14:15:00Z',
  },
  {
    id: 'issue-04',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    bookId: 'book-03',
    bookTitle: 'The Unfinished Memoirs',
    accessionNumber: 'ACC-2026-003',
    borrowerType: 'student',
    borrowerId: 'stu-03',
    borrowerName: 'Rahim Uddin',
    borrowerRollOrDesignation: 'Roll: 05',
    borrowerClass: 'Class 9',
    issueDate: '2026-08-01',
    dueDate: '2026-08-15',
    returnDate: '2026-08-14',
    status: 'returned',
    finePerDay: 2,
    fineAmount: 0,
    finePaid: true,
    issuedBy: 'Md. Shafiqur Rahman (Librarian)',
    createdAt: '2026-08-01T10:00:00Z',
  },
];

// ==========================================
// 3. SAMPLE INVENTORY ITEMS (EQUIPMENT & ASSETS)
// ==========================================
export const SAMPLE_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'inv-01',
    instituteId: 'inst-01',
    itemCode: 'INV-FURN-001',
    name: 'Dual High-Low Wooden Bench (Student)',
    bengaliName: 'কাঠের জোড়া হাই-লো বেঞ্চ',
    category: 'furniture',
    roomOrLocation: 'Classroom 10-A (Room 204)',
    quantity: 25,
    unit: 'Sets',
    unitCost: 4500,
    totalValuation: 112500,
    purchaseDate: '2024-03-15',
    supplierOrVendor: 'Al-Madina Timber & Furniture, Dhaka',
    condition: 'good',
    notes: 'Regular polish done in Jan 2026',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'inv-02',
    instituteId: 'inst-01',
    itemCode: 'INV-IT-002',
    name: 'Desktop PC (Core i5, 16GB, SSD 512GB)',
    bengaliName: 'কম্পিউটার ডেস্কটপ (আই-৫)',
    category: 'computer_it',
    roomOrLocation: 'Sheikh Russel Digital Computer Lab',
    quantity: 20,
    unit: 'Units',
    unitCost: 48000,
    totalValuation: 960000,
    purchaseDate: '2023-11-20',
    supplierOrVendor: 'Smart Technologies BD Ltd.',
    condition: 'good',
    warrantyExpiry: '2026-11-20',
    notes: 'Equipped with Windows 11 & Python IDE',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'inv-03',
    instituteId: 'inst-01',
    itemCode: 'INV-LAB-003',
    name: 'Monocular Biological Microscope (1000x)',
    bengaliName: 'জীববিজ্ঞান অণুবীক্ষণ যন্ত্র',
    category: 'science_lab',
    roomOrLocation: 'Biology & Zoology Laboratory',
    quantity: 12,
    unit: 'Pcs',
    unitCost: 11500,
    totalValuation: 138000,
    purchaseDate: '2024-01-18',
    supplierOrVendor: 'Scientific Traders Co., Nawabpur',
    condition: 'good',
    notes: 'Serviced bi-annually',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'inv-04',
    instituteId: 'inst-01',
    itemCode: 'INV-ELEC-004',
    name: 'Epson Interactive Multimedia Projector',
    bengaliName: 'মাল্টিমিডিয়া প্রজেক্টর',
    category: 'electrical_electronics',
    roomOrLocation: 'Auditorium & Audio-Visual Room',
    quantity: 3,
    unit: 'Units',
    unitCost: 65000,
    totalValuation: 195000,
    purchaseDate: '2025-02-10',
    supplierOrVendor: 'Flora Limited, Motijheel',
    condition: 'good',
    warrantyExpiry: '2027-02-10',
    notes: 'HDMI ceiling mount connection',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'inv-05',
    instituteId: 'inst-01',
    itemCode: 'INV-SPORT-005',
    name: 'Tournament Cricket Kit Bag & Leather Balls',
    bengaliName: 'ক্রিকেট কিট ব্যাগ ও লেদার বল',
    category: 'sports_equipment',
    roomOrLocation: 'Physical Education Store Room',
    quantity: 4,
    unit: 'Sets',
    unitCost: 18500,
    totalValuation: 74000,
    purchaseDate: '2025-11-05',
    supplierOrVendor: 'Stadium Market Sports, Gulistan',
    condition: 'fair',
    notes: 'Includes bats, pads, gloves, and helmets',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'inv-06',
    instituteId: 'inst-01',
    itemCode: 'INV-FURN-006',
    name: 'Executive Revolving Chair (Teachers Room)',
    bengaliName: 'রিভলভিং চেয়ার (শিক্ষক কক্ষ)',
    category: 'furniture',
    roomOrLocation: 'Teachers Common Room',
    quantity: 18,
    unit: 'Pcs',
    unitCost: 7500,
    totalValuation: 135000,
    purchaseDate: '2023-05-12',
    supplierOrVendor: 'Otobi Limited',
    condition: 'needs_repair',
    notes: '2 chairs hydraulic wheel replacement pending',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
];

export const SAMPLE_INVENTORY_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: 'tx-01',
    instituteId: 'inst-01',
    itemId: 'inv-01',
    itemName: 'Dual High-Low Wooden Bench (Student)',
    transactionType: 'issue',
    quantity: 5,
    fromLocation: 'Central Store Room',
    toLocation: 'Classroom 10-A',
    handledBy: 'Abul Kashem (Caregiver)',
    date: '2026-01-15',
    remarks: 'Added due to increased section enrollment',
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'tx-02',
    instituteId: 'inst-01',
    itemId: 'inv-06',
    itemName: 'Executive Revolving Chair (Teachers Room)',
    transactionType: 'repair',
    quantity: 2,
    fromLocation: 'Teachers Common Room',
    toLocation: 'Maintenance Workshop',
    handledBy: 'Kawsar Mia (Technician)',
    date: '2026-02-04',
    remarks: 'Hydraulic wheel replacement scheduled',
    cost: 1400,
    createdAt: '2026-02-04T11:30:00Z',
  },
];

// ==========================================
// 4. SAMPLE VEHICLES & TRANSPORT
// ==========================================
export const SAMPLE_VEHICLES: VehicleItem[] = [
  {
    id: 'veh-01',
    instituteId: 'inst-01',
    registrationNumber: 'ঢাকা মেট্রো-চ ১১-৮৮৯০',
    vehicleType: 'bus',
    capacity: 45,
    driverName: 'Mohammad Rafiqul Islam',
    driverPhone: '01711-234567',
    driverLicenseNumber: 'DL-DK-89342',
    helperName: 'Sumon Mia',
    helperPhone: '01912-345678',
    fitnessExpiryDate: '2027-04-30',
    taxTokenExpiryDate: '2026-12-31',
    routeId: 'route-01',
    routeName: 'Route 1: Mirpur-10 to Campus',
    status: 'active',
    createdAt: '2026-01-05T08:00:00Z',
    updatedAt: '2026-01-05T08:00:00Z',
  },
  {
    id: 'veh-02',
    instituteId: 'inst-01',
    registrationNumber: 'ঢাকা মেট্রো-চ ১৪-২৩৪৫',
    vehicleType: 'minibus',
    capacity: 32,
    driverName: 'Abdul Jalil',
    driverPhone: '01822-456789',
    driverLicenseNumber: 'DL-DK-45812',
    helperName: 'Rasel Ahmed',
    helperPhone: '01633-876543',
    fitnessExpiryDate: '2027-02-15',
    taxTokenExpiryDate: '2026-11-30',
    routeId: 'route-02',
    routeName: 'Route 2: Uttara to Campus',
    status: 'active',
    createdAt: '2026-01-05T08:00:00Z',
    updatedAt: '2026-01-05T08:00:00Z',
  },
  {
    id: 'veh-03',
    instituteId: 'inst-01',
    registrationNumber: 'ঢাকা মেট্রো-ঘ ৫২-৭৮১২',
    vehicleType: 'microbus',
    capacity: 14,
    driverName: 'Golam Kibria',
    driverPhone: '01733-987654',
    driverLicenseNumber: 'DL-DK-23901',
    fitnessExpiryDate: '2026-10-15',
    taxTokenExpiryDate: '2026-12-15',
    routeId: 'route-03',
    routeName: 'Route 3: Dhanmondi to Campus',
    status: 'active',
    createdAt: '2026-01-05T08:00:00Z',
    updatedAt: '2026-01-05T08:00:00Z',
  },
];

export const SAMPLE_ROUTES: TransportRoute[] = [
  {
    id: 'route-01',
    instituteId: 'inst-01',
    routeName: 'Route 1: Mirpur-10 to Campus',
    bengaliRouteName: 'রুট ১: মিরপুর-১০ হতে ক্যাম্পাস',
    startPoint: 'Mirpur-10 Golchokkor',
    destination: 'Campus Main Gate',
    vehicleId: 'veh-01',
    vehicleReg: 'ঢাকা মেট্রো-চ ১১-৮৮৯০',
    driverName: 'Mohammad Rafiqul Islam',
    driverPhone: '01711-234567',
    status: 'active',
    stoppages: [
      { id: 'stp-101', name: 'Mirpur-10 Roundabout', bengaliName: 'মিরপুর-১০ গোলচত্বর', pickupTime: '06:50 AM', dropTime: '03:10 PM', monthlyFare: 1500 },
      { id: 'stp-102', name: 'Kazipara Bus Stop', bengaliName: 'কাজীপাড়া বাসস্ট্যান্ড', pickupTime: '07:05 AM', dropTime: '02:55 PM', monthlyFare: 1400 },
      { id: 'stp-103', name: 'Shewrapara Metro Station', bengaliName: 'শেওড়াপাড়া স্টেশন', pickupTime: '07:15 AM', dropTime: '02:45 PM', monthlyFare: 1300 },
      { id: 'stp-104', name: 'Agargaon T&T Colony', bengaliName: 'আগারগাঁও টিএন্ডটি', pickupTime: '07:30 AM', dropTime: '02:30 PM', monthlyFare: 1200 },
      { id: 'stp-105', name: 'Bijoy Sarani Overbridge', bengaliName: 'বিজয় সরণি ওভারব্রিজ', pickupTime: '07:45 AM', dropTime: '02:15 PM', monthlyFare: 1000 },
    ],
    createdAt: '2026-01-05T08:30:00Z',
    updatedAt: '2026-01-05T08:30:00Z',
  },
  {
    id: 'route-02',
    instituteId: 'inst-01',
    routeName: 'Route 2: Uttara to Campus',
    bengaliRouteName: 'রুট ২: উত্তরা হতে ক্যাম্পাস',
    startPoint: 'Uttara House Building (Sector 7)',
    destination: 'Campus Main Gate',
    vehicleId: 'veh-02',
    vehicleReg: 'ঢাকা মেট্রো-চ ১৪-২৩৪৫',
    driverName: 'Abdul Jalil',
    driverPhone: '01822-456789',
    status: 'active',
    stoppages: [
      { id: 'stp-201', name: 'House Building Sector 7', bengaliName: 'হাউজ বিল্ডিং সেক্টর ৭', pickupTime: '06:40 AM', dropTime: '03:20 PM', monthlyFare: 1800 },
      { id: 'stp-202', name: 'Azampur Bus Stand', bengaliName: 'আজমপুর বাসস্ট্যান্ড', pickupTime: '06:55 AM', dropTime: '03:05 PM', monthlyFare: 1700 },
      { id: 'stp-203', name: 'Airport / Kawla Overpass', bengaliName: 'বিমানবন্দর / কাওলা', pickupTime: '07:10 AM', dropTime: '02:50 PM', monthlyFare: 1500 },
      { id: 'stp-204', name: 'Khilkhet Foot Overbridge', bengaliName: 'খিলক্ষেত ফুট ওভারব্রিজ', pickupTime: '07:25 AM', dropTime: '02:35 PM', monthlyFare: 1300 },
      { id: 'stp-205', name: 'Kuril Bishwa Road', bengaliName: 'কুড়িল বিশ্বরোড', pickupTime: '07:35 AM', dropTime: '02:25 PM', monthlyFare: 1200 },
    ],
    createdAt: '2026-01-05T08:30:00Z',
    updatedAt: '2026-01-05T08:30:00Z',
  },
];

export const SAMPLE_TRANSPORT_ASSIGNMENTS: TransportAssignment[] = [
  {
    id: 't-assign-01',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-01',
    studentName: 'Tanvir Ahmed',
    className: 'Class 10',
    rollNumber: 1,
    routeId: 'route-01',
    routeName: 'Route 1: Mirpur-10 to Campus',
    stoppageId: 'stp-101',
    stoppageName: 'Mirpur-10 Roundabout',
    monthlyFee: 1500,
    assignedDate: '2026-01-10',
    status: 'active',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 't-assign-02',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    studentId: 'stu-02',
    studentName: 'Nusrat Jahan',
    className: 'Class 10',
    rollNumber: 2,
    routeId: 'route-02',
    routeName: 'Route 2: Uttara to Campus',
    stoppageId: 'stp-202',
    stoppageName: 'Azampur Bus Stand',
    monthlyFee: 1700,
    assignedDate: '2026-01-12',
    status: 'active',
    createdAt: '2026-01-12T11:00:00Z',
  },
];

// ==========================================
// 5. SAMPLE NOTICES (NOTICE BOARD)
// ==========================================
export const SAMPLE_NOTICES: SchoolNotice[] = [
  {
    id: 'not-01',
    instituteId: 'inst-01',
    noticeNumber: 'SCH/NOT/2026/089',
    title: 'Schedule for Half-Yearly Examination 2026 & Admit Card Collection',
    bengaliTitle: 'অর্ধ-বার্ষিক পরীক্ষা ২০২৬ এর সময়সূচি ও প্রবেশপত্র বিতরণ সংক্রান্ত',
    category: 'examination',
    audience: 'all',
    content:
      'This is to notify all students from Class 6 through Class 10 that the Half-Yearly Examination 2026 will commence from October 15, 2026. Students must clear all outstanding tuition and exam fees up to September by October 05 to receive their official Admit Cards from the respective Class Teachers. No student will be allowed to sit for examinations without a verified Admit Card.',
    contentBengali:
      'এতদ্বারা ৬ষ্ঠ থেকে ১০ম শ্রেণির সকল শিক্ষার্থী ও সম্মানিত অভিভাবকদের অবগতির জন্য জানানো যাচ্ছে যে, আগামী ১৫ অক্টোবর ২০২৬ তারিখ থেকে প্রতিষ্ঠানটির অর্ধ-বার্ষিক পরীক্ষা শুরু হবে। সকল শিক্ষার্থীকে আগামী ০৫ অক্টোবর ২০২৬ তারিখের মধ্যে সেপ্টেম্বর মাস পর্যন্ত যাবতীয় বকেয়া বেতন ও পরীক্ষার ফি পরিশোধ করে শ্রেণি শিক্ষকের নিকট থেকে প্রবেশপত্র (Admit Card) সংগ্রহের নির্দেশ দেওয়া যাচ্ছে। প্রবেশপত্র ব্যতিরেকে কোনো শিক্ষার্থীকে পরীক্ষা কেন্দ্রে প্রবেশ করতে দেওয়া হবে না।',
    priority: 'urgent',
    publishDate: '2026-09-10',
    expiryDate: '2026-10-31',
    isPinned: true,
    signedBy: 'Principal / Headmaster',
    signerDesignation: 'Head of Institution',
    status: 'published',
    attachmentName: 'Half_Yearly_Exam_Routine_2026.pdf',
    createdAt: '2026-09-10T09:00:00Z',
    updatedAt: '2026-09-10T09:00:00Z',
  },
  {
    id: 'not-02',
    instituteId: 'inst-01',
    noticeNumber: 'SCH/NOT/2026/085',
    title: 'Observance of National Mourning Day & Shaheed Memorial Discussion',
    bengaliTitle: 'জাতীয় শোক দিবস ও আলোচনা সভা অনুষ্ঠান',
    category: 'academic',
    audience: 'all',
    content:
      'In observance of National Mourning, the institution will organize a discussion meeting, essay competition, and Dua Mahfil. Attendance is mandatory for all students, teachers, and staff in prescribed formal uniform.',
    contentBengali:
      'যথাযোগ্য মর্যাদায় দিবসটি পালনের লক্ষ্যে প্রতিষ্ঠানের মিলনায়তনে আলোচনা সভা, রচনা প্রতিযোগিতা ও বিশেষ দোয়া মাহফিলের আয়োজন করা হয়েছে। সকল শিক্ষক, কর্মচারী ও শিক্ষার্থীদের যথাসময়ে উপস্থিত থাকার জন্য অনুরোধ করা হলো।',
    priority: 'high',
    publishDate: '2026-08-12',
    expiryDate: '2026-08-16',
    isPinned: false,
    signedBy: 'Convener, National Observance Committee',
    signerDesignation: 'Senior Teacher',
    status: 'published',
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'not-03',
    instituteId: 'inst-01',
    noticeNumber: 'SCH/NOT/2026/082',
    title: 'Inter-School Science Fair & Robotics Exhibition Registration',
    bengaliTitle: 'আন্তঃস্কুল বিজ্ঞান মেলা ও রোবোটিক্স প্রদর্শনীতে নিবন্ধন',
    category: 'sports_cultural',
    audience: 'students',
    content:
      'Students interested in showcasing Science Projects, AI Innovations, and Robotics models in the upcoming Annual Science Fest are requested to register their team (max 3 members) with the Science Club coordinator Dr. Azizul Hoque by September 25, 2026.',
    contentBengali:
      'আসন্ন বার্ষিক বিজ্ঞান মেলায় বিজ্ঞান প্রজেক্ট, এআই ইনোভেশন ও রোবোটিক্স মডেল প্রদর্শনে আগ্রহী শিক্ষার্থীদের আগামী ২৫ সেপ্টেম্বর ২০২৬ তারিখের মধ্যে বিজ্ঞান ক্লাবের সমন্বয়ক ড. আজিজুল হকের নিকট ৩ সদস্যের দল নিবন্ধন সম্পন্ন করার নির্দেশ দেওয়া যাচ্ছে।',
    priority: 'normal',
    publishDate: '2026-09-01',
    expiryDate: '2026-09-30',
    isPinned: false,
    signedBy: 'Science Club Coordinator',
    signerDesignation: 'Lecturer in Physics',
    status: 'published',
    createdAt: '2026-09-01T11:00:00Z',
    updatedAt: '2026-09-01T11:00:00Z',
  },
  {
    id: 'not-04',
    instituteId: 'inst-01',
    noticeNumber: 'SCH/NOT/2026/078',
    title: 'Mandatory Student Uniform and Smart ID Card Compliance',
    bengaliTitle: 'শিক্ষার্থীদের নির্ধারিত ইউনিফর্ম ও স্মার্ট আইডি কার্ড পরিধান সংক্রান্ত',
    category: 'urgent_special',
    audience: 'all',
    content:
      'All students must wear the institution’s official uniform and display their Barcode-enabled CR80 Smart ID Card visibly around their neck while entering campus. Security and Turnstiles will enforce strict check-in from next Sunday.',
    contentBengali:
      'ক্যাম্পাসে প্রবেশের সময় সকল শিক্ষার্থীকে অবশ্যই নির্ধারিত প্রাতিষ্ঠানিক ইউনিফর্ম পরিধান করতে হবে এবং বারকোডযুক্ত স্মার্ট আইডি কার্ড দৃশ্যমানভাবে ঝুলিয়ে রাখতে হবে। আগামী রবিবার থেকে প্রধান ফটকে নিরাপত্তা কর্মীরা কড়াকড়িভাবে এটি নিশ্চিত করবেন।',
    priority: 'high',
    publishDate: '2026-08-28',
    expiryDate: '2026-10-15',
    isPinned: false,
    signedBy: 'Discipline Committee & Headmaster',
    signerDesignation: 'Chief Proctor',
    status: 'published',
    createdAt: '2026-08-28T08:30:00Z',
    updatedAt: '2026-08-28T08:30:00Z',
  },
];

// ==========================================
// 6. SAMPLE CALENDAR EVENTS & HOLIDAYS (2026 BANGLADESH)
// ==========================================
export const SAMPLE_CALENDAR_EVENTS: CalendarEventItem[] = [
  {
    id: 'cal-01',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'International Mother Language Day & Shaheed Dibash',
    bengaliTitle: 'আন্তর্জাতিক মাতৃভাষা দিবস ও শহীদ দিবস',
    eventType: 'national_observance',
    startDate: '2026-02-21',
    endDate: '2026-02-21',
    durationDays: 1,
    isGovernmentHoliday: true,
    description: 'National holiday & Prabhat Pheri ceremony at Shaheed Minar',
    colorTag: 'bg-rose-500',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cal-02',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'Independence & National Day of Bangladesh',
    bengaliTitle: 'স্বাধীনতা ও জাতীয় দিবস',
    eventType: 'national_observance',
    startDate: '2026-03-26',
    endDate: '2026-03-26',
    durationDays: 1,
    isGovernmentHoliday: true,
    description: 'Flag hoisting, march-past, and national tribute',
    colorTag: 'bg-red-600',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cal-03',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'Holy Eid-ul-Fitr & Shab-e-Qadr Vacation',
    bengaliTitle: 'পবিত্র ঈদুল ফিতর ও শবে ক্বদর ছুটি',
    eventType: 'vacation',
    startDate: '2026-03-18',
    endDate: '2026-03-24',
    durationDays: 7,
    isGovernmentHoliday: true,
    description: 'Institutional academic recess for Eid festivities',
    colorTag: 'bg-emerald-600',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cal-04',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'Bangla Nabobarsho (Pahela Baishakh 1433)',
    bengaliTitle: 'পহেলা বৈশাখ (বাংলা নববর্ষ ১৪৩৩)',
    eventType: 'cultural_event',
    startDate: '2026-04-14',
    endDate: '2026-04-14',
    durationDays: 1,
    isGovernmentHoliday: true,
    description: 'Traditional Mangal Shobhajatra and cultural festival on campus',
    colorTag: 'bg-amber-500',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cal-05',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'May Day (International Workers’ Day)',
    bengaliTitle: 'মে দিবস (আন্তর্জাতিক শ্রমিক দিবস)',
    eventType: 'government_holiday',
    startDate: '2026-05-01',
    endDate: '2026-05-01',
    durationDays: 1,
    isGovernmentHoliday: true,
    description: 'Public holiday',
    colorTag: 'bg-blue-600',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cal-06',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'Holy Eid-ul-Adha Vacation',
    bengaliTitle: 'পবিত্র ঈদুল আযহা ছুটি',
    eventType: 'vacation',
    startDate: '2026-05-26',
    endDate: '2026-06-01',
    durationDays: 7,
    isGovernmentHoliday: true,
    description: 'Qurbani Eid religious holiday and campus recess',
    colorTag: 'bg-teal-600',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cal-07',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'Half-Yearly / Mid-Term Examinations 2026',
    bengaliTitle: 'অর্ধ-বার্ষিক পরীক্ষা ২০২৬',
    eventType: 'academic_exam',
    startDate: '2026-10-15',
    endDate: '2026-10-29',
    durationDays: 15,
    isGovernmentHoliday: false,
    description: 'Comprehensive mid-term evaluation across all classes',
    colorTag: 'bg-purple-600',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cal-08',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'Durga Puja (Bijoya Dashami) Holiday',
    bengaliTitle: 'শুভ দুর্গাপূজা (বিজয়া দশমী)',
    eventType: 'government_holiday',
    startDate: '2026-10-20',
    endDate: '2026-10-22',
    durationDays: 3,
    isGovernmentHoliday: true,
    description: 'Hindu religious festival holiday',
    colorTag: 'bg-orange-500',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cal-09',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'Annual Sports & Athletics Meet 2026',
    bengaliTitle: 'বার্ষিক ক্রীড়া ও দৌড় প্রতিযোগিতা ২০২৬',
    eventType: 'sports_competition',
    startDate: '2026-11-20',
    endDate: '2026-11-21',
    durationDays: 2,
    isGovernmentHoliday: false,
    description: 'Track and field competition on institutional playground',
    colorTag: 'bg-indigo-600',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cal-10',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'Victory Day (Bijoy Dibash)',
    bengaliTitle: 'মহান বিজয় দিবস',
    eventType: 'national_observance',
    startDate: '2026-12-16',
    endDate: '2026-12-16',
    durationDays: 1,
    isGovernmentHoliday: true,
    description: 'National Victory Day celebrations and flag salute',
    colorTag: 'bg-red-700',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cal-11',
    instituteId: 'inst-01',
    academicYearId: 'ay-2026',
    title: 'Winter & Year-End Vacation 2026',
    bengaliTitle: 'শীতকালীন ও বার্ষিক অবকাশ',
    eventType: 'vacation',
    startDate: '2026-12-24',
    endDate: '2026-12-31',
    durationDays: 8,
    isGovernmentHoliday: true,
    description: 'Winter vacation and academic preparation for 2027 session',
    colorTag: 'bg-sky-600',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
];
